---
- name: Converge
  hosts: all
  become: true

  roles:
    - role: eirikns.caddy
      vars:
        caddy_acme_email: "admin@example.com"
        caddy_acme_ca: "https://acme-staging-v02.api.letsencrypt.org/directory"
        caddy_vhosts:
          - domain: ":8080"
            reverse_proxy: "localhost:8081"
            dial_timeout: "10s"
            response_header_timeout: "120s"
            encode: true
